name: yesod-except
version: "0.0.0"

dependencies:
# Library dependencies:
- base >=4.6 && < 4.10
- aeson
- classy-prelude-yesod
- conduit-extra
- mtl
- text
- blaze-markup
# Extra dependencies for examples:
- yesod

library:
  
  source-dirs: src
  
  ghc-options:
  - -Wall
  - -fwarn-tabs
  - -O2
  
executables:
  math:
    main: Main.hs
    source-dirs: example/math
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yesod-except
